# Generated by Django 3.2.2 on 2021-05-17 06:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addmission', '0008_alter_addmission_details_pending_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('photo', models.ImageField(blank=True, upload_to='images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'], 'File extension is invalid')])),
                ('addmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='addmission.addmission_details')),
            ],
        ),
    ]
